language: java
sudo: false

jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk7

install: true

branches:
  only:
    - master

script: mvn clean test jacoco:report

after_success:
  - mvn coveralls:report
